BLOG_SUMMER_SPORTS: list[str] = [
    "American Football", 
    "Archery", 
    "Artistic Swimming", 
    "Badminton", 
    "Baseball",
    "Basketball", 
    "Canoe Sprint", 
    "Cricket", 
    "Cycling", 
    "Diving", 
    "Fencing", 
    "Football (Soccer)",
    "Golf", 
    "Gymnastics",
    "Handball", 
    "Hockey (Ice)", 
    "Hockey (Field)",
    "Lacrosse", 
    "Marital Arts",
    "Rowing",
    "Rugby", 
    "Sailing", 
    "Shooting", 
    "Skateboarding", 
    "Sport Climbing",
    "Squash", 
    "Surfing", 
    "Swimming", 
    "Table Tennis",
    "Tennis", 
    "Triathlon", 
    "Volleyball",
    "Water Polo", 
    "Weightlifting", 
    "Wrestling",
]

BLOG_WINTER_SPORTS: list[str] = [
    "Alpine Skiing",
    "Biathlon", 
    "Bobsleigh", 
    "Cross-Country Skiing",
    "Curling", 
    "Figure Skating", 
    "Freestyle Skiing", 
    "Ice Hockey",
    "Luge", 
    "Nordic Combined", 
    "Speed Skating",
    "Ski Jumping", 
    "Snowboard", 
]